TIMEOUT 30
DEFAULT alpine

LABEL alpine
    MENU LABEL Alpine Linux
    LINUX /vmlinuz
    FDT /dtbs/qcom/msm8916-jz01-45-v33.dtb
    APPEND earlycon root=PARTUUID=a7ab80e8-e9d1-e8cd-f157-93f69b1d141e console=ttyMSM0,115200 no_framebuffer=true rw rootwait